#! /bin/bash                                                                                                                                                                     

DefInFile="slhaspectrum.in"

if [ $# -gt 0 ] ; then
    DefInFile=$1
fi

#sparticle previous to gravitino
PATTERN='1000037'

GRAVMASS=2.24350000E-07  #Fixed for now

if [ $# -gt 1 ] ; then
    GRAVMASS=$2
fi

NEWLINE="\\\   1000039     "$GRAVMASS"   \# \~gravitino"

#grep $PATTERN $DefInFile
sed -i "/1000037/ a\
${NEWLINE}" $DefInFile 

# > $DefInFile'_tmp'; mv $DefInFile"_tmp" $DefInFile

